<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-09-22 19:22:24
 * @LastEditors: by_mori
 * @LastEditTime: 2021-09-22 19:26:43
-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>catch方法</title>
  </head>
  <body>
    <script>
      const p = new Promise((resolve, reject) => {
        setTimeout(() => {
          //设置 p 对象的状态为失败, 并设置失败的值
          reject('出错了！');
        }, 1000);
      });

      //   p.then(
      //     function (value) {},
      //     function (reason) {
      //       console.error(reason);
      //     }
      //   );

      p.catch(function (reason) {
        console.warn(reason);
      });
    </script>
  </body>
</html>
